"""phase14_add_job_tracking_to_analysis_runs

Revision ID: 4f6d82e5ebcc
Revises: a7b3c9d2e5f1
Create Date: 2026-09-23 09:44:58.198137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f6d82e5ebcc'
down_revision: Union[str, None] = 'a7b3c9d2e5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=511), nullable=False),
    sa.Column('github_url', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index('idx_repositories_full_name', 'repositories', ['full_name'], unique=False)
    op.create_index('idx_repositories_owner', 'repositories', ['owner'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'pending', 'running', 'completed', 'failed', 'cancelled', name='analysisstatus'), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.String(length=255), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('analyzed_files', sa.Integer(), nullable=True),
    sa.Column('total_symbols', sa.Integer(), nullable=True),
    sa.Column('total_imports', sa.Integer(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_runs_job_id', 'analysis_runs', ['job_id'], unique=False)
    op.create_index('idx_analysis_runs_repository_id', 'analysis_runs', ['repository_id'], unique=False)
    op.create_index('idx_analysis_runs_started_at', 'analysis_runs', ['started_at'], unique=False)
    op.create_index('idx_analysis_runs_status', 'analysis_runs', ['status'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.Column('parent_hashes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'commit_hash', name='uq_commits_repository_hash')
    )
    op.create_index('idx_commits_author_email', 'commits', ['author_email'], unique=False)
    op.create_index('idx_commits_commit_hash', 'commits', ['commit_hash'], unique=False)
    op.create_index('idx_commits_committed_at', 'commits', ['committed_at'], unique=False)
    op.create_index('idx_commits_repository_id', 'commits', ['repository_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'path', name='uq_files_analysis_run_path')
    )
    op.create_index('idx_files_analysis_run_id', 'files', ['analysis_run_id'], unique=False)
    op.create_index('idx_files_language', 'files', ['language'], unique=False)
    op.create_index('idx_files_path', 'files', ['path'], unique=False)
    op.create_index('idx_files_repository_id', 'files', ['repository_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('contains', 'imports', 'calls', name='relationshiptype'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_name', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_relationships_analysis_run_id', 'relationships', ['analysis_run_id'], unique=False)
    op.create_index('idx_relationships_source', 'relationships', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_relationships_target', 'relationships', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_relationships_type', 'relationships', ['relationship_type'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('caller_name', sa.String(length=255), nullable=False),
    sa.Column('callee_name', sa.String(length=255), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calls_analysis_run_id', 'calls', ['analysis_run_id'], unique=False)
    op.create_index('idx_calls_callee_name', 'calls', ['callee_name'], unique=False)
    op.create_index('idx_calls_caller_name', 'calls', ['caller_name'], unique=False)
    op.create_index('idx_calls_file_id', 'calls', ['file_id'], unique=False)
    op.create_table('commit_file_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commit_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('change_type', sa.Enum('added', 'modified', 'deleted', 'renamed', name='changetype'), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('old_path', sa.String(length=1024), nullable=True),
    sa.Column('new_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commit_file_changes_commit_id', 'commit_file_changes', ['commit_id'], unique=False)
    op.create_index('idx_commit_file_changes_file_id', 'commit_file_changes', ['file_id'], unique=False)
    op.create_index('idx_commit_file_changes_path', 'commit_file_changes', ['path'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=1024), nullable=False),
    sa.Column('imported_names', sa.Text(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_imports_analysis_run_id', 'imports', ['analysis_run_id'], unique=False)
    op.create_index('idx_imports_file_id', 'imports', ['file_id'], unique=False)
    op.create_index('idx_imports_source', 'imports', ['source'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol_type', sa.Enum('function', 'class', 'method', 'arrow_function', 'interface', name='symboltype'), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('parent_symbol_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_symbol_id'], ['symbols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbols_analysis_run_id', 'symbols', ['analysis_run_id'], unique=False)
    op.create_index('idx_symbols_file_id', 'symbols', ['file_id'], unique=False)
    op.create_index('idx_symbols_name', 'symbols', ['name'], unique=False)
    op.create_index('idx_symbols_parent_symbol_id', 'symbols', ['parent_symbol_id'], unique=False)
    op.create_index('idx_symbols_type', 'symbols', ['symbol_type'], unique=False)
    op.create_table('api_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD', name='httpmethod'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('handler_name', sa.String(length=255), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'method', 'path', name='uq_api_endpoints_analysis_run_method_path')
    )
    op.create_index('idx_api_endpoints_analysis_run_id', 'api_endpoints', ['analysis_run_id'], unique=False)
    op.create_index('idx_api_endpoints_file_id', 'api_endpoints', ['file_id'], unique=False)
    op.create_index('idx_api_endpoints_framework', 'api_endpoints', ['framework'], unique=False)
    op.create_index('idx_api_endpoints_method', 'api_endpoints', ['method'], unique=False)
    op.create_index('idx_api_endpoints_path', 'api_endpoints', ['path'], unique=False)
    op.create_index('idx_api_endpoints_repository_id', 'api_endpoints', ['repository_id'], unique=False)
    op.create_index('idx_api_endpoints_symbol_id', 'api_endpoints', ['symbol_id'], unique=False)
    op.create_table('semantic_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('api_endpoint_id', sa.UUID(), nullable=True),
    sa.Column('chunk_type', sa.Enum('symbol', 'api_endpoint', 'documentation', 'file', name='chunktype'), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['api_endpoint_id'], ['api_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'content_hash', 'chunk_index', name='uq_semantic_chunks_analysis_run_hash_index')
    )
    op.create_index('idx_semantic_chunks_analysis_run_id', 'semantic_chunks', ['analysis_run_id'], unique=False)
    op.create_index('idx_semantic_chunks_api_endpoint_id', 'semantic_chunks', ['api_endpoint_id'], unique=False)
    op.create_index('idx_semantic_chunks_chunk_type', 'semantic_chunks', ['chunk_type'], unique=False)
    op.create_index('idx_semantic_chunks_content_hash', 'semantic_chunks', ['content_hash'], unique=False)
    op.create_index('idx_semantic_chunks_file_id', 'semantic_chunks', ['file_id'], unique=False)
    op.create_index('idx_semantic_chunks_repository_id', 'semantic_chunks', ['repository_id'], unique=False)
    op.create_index('idx_semantic_chunks_symbol_id', 'semantic_chunks', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_semantic_chunks_symbol_id', table_name='semantic_chunks')
    op.drop_index('idx_semantic_chunks_repository_id', table_name='semantic_chunks')
    op.drop_index('idx_semantic_chunks_file_id', table_name='semantic_chunks')
    op.drop_index('idx_semantic_chunks_content_hash', table_name='semantic_chunks')
    op.drop_index('idx_semantic_chunks_chunk_type', table_name='semantic_chunks')
    op.drop_index('idx_semantic_chunks_api_endpoint_id', table_name='semantic_chunks')
    op.drop_index('idx_semantic_chunks_analysis_run_id', table_name='semantic_chunks')
    op.drop_table('semantic_chunks')
    op.drop_index('idx_api_endpoints_symbol_id', table_name='api_endpoints')
    op.drop_index('idx_api_endpoints_repository_id', table_name='api_endpoints')
    op.drop_index('idx_api_endpoints_path', table_name='api_endpoints')
    op.drop_index('idx_api_endpoints_method', table_name='api_endpoints')
    op.drop_index('idx_api_endpoints_framework', table_name='api_endpoints')
    op.drop_index('idx_api_endpoints_file_id', table_name='api_endpoints')
    op.drop_index('idx_api_endpoints_analysis_run_id', table_name='api_endpoints')
    op.drop_table('api_endpoints')
    op.drop_index('idx_symbols_type', table_name='symbols')
    op.drop_index('idx_symbols_parent_symbol_id', table_name='symbols')
    op.drop_index('idx_symbols_name', table_name='symbols')
    op.drop_index('idx_symbols_file_id', table_name='symbols')
    op.drop_index('idx_symbols_analysis_run_id', table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('idx_imports_source', table_name='imports')
    op.drop_index('idx_imports_file_id', table_name='imports')
    op.drop_index('idx_imports_analysis_run_id', table_name='imports')
    op.drop_table('imports')
    op.drop_index('idx_commit_file_changes_path', table_name='commit_file_changes')
    op.drop_index('idx_commit_file_changes_file_id', table_name='commit_file_changes')
    op.drop_index('idx_commit_file_changes_commit_id', table_name='commit_file_changes')
    op.drop_table('commit_file_changes')
    op.drop_index('idx_calls_file_id', table_name='calls')
    op.drop_index('idx_calls_caller_name', table_name='calls')
    op.drop_index('idx_calls_callee_name', table_name='calls')
    op.drop_index('idx_calls_analysis_run_id', table_name='calls')
    op.drop_table('calls')
    op.drop_index('idx_relationships_type', table_name='relationships')
    op.drop_index('idx_relationships_target', table_name='relationships')
    op.drop_index('idx_relationships_source', table_name='relationships')
    op.drop_index('idx_relationships_analysis_run_id', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index('idx_files_repository_id', table_name='files')
    op.drop_index('idx_files_path', table_name='files')
    op.drop_index('idx_files_language', table_name='files')
    op.drop_index('idx_files_analysis_run_id', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_commits_repository_id', table_name='commits')
    op.drop_index('idx_commits_committed_at', table_name='commits')
    op.drop_index('idx_commits_commit_hash', table_name='commits')
    op.drop_index('idx_commits_author_email', table_name='commits')
    op.drop_table('commits')
    op.drop_index('idx_analysis_runs_status', table_name='analysis_runs')
    op.drop_index('idx_analysis_runs_started_at', table_name='analysis_runs')
    op.drop_index('idx_analysis_runs_repository_id', table_name='analysis_runs')
    op.drop_index('idx_analysis_runs_job_id', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index('idx_repositories_owner', table_name='repositories')
    op.drop_index('idx_repositories_full_name', table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
